import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppHeader from "@/components/AppHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quiz App - Learn Better",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 1. Эхлээд env-ээс уншиж үзнэ, хэрэв байхгүй бол шууд утгыг нь онооно
  const clerkKey =
    process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY ||
    "pk_test_bmljZS1kb2ctNzAuY2xlcmsuYWNjb3VudHMuZGV2JA";

  console.log("Building with Key:", clerkKey ? "Key exists" : "Key is missing");

  return (
    <ClerkProvider publishableKey={clerkKey}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <AppHeader />
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
